name: cron

on:

  workflow_dispatch:

  schedule:

    - cron: "* */24 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  cron:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2 

      - name: cron

        run: cd $HOME/work/epgguide/epgguide/ && python3 service.py

      - uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: cron
